### ISSUE TITLE
error[E0599]: no method named `color` found for reference `&serde_json::Value` in the current scope

### ISSUE THREAD

**Issue by jmshgs** [ihateblueb/cobalt-cli#4]
<img width="1415" alt="SCR-20230918-oyhd" src="https://github.com/ihateblueb/cobalt-cli/assets/72482214/577e3f49-fdb4-4481-930b-a7bea489afb9">
getting this error when using `cargo build`. 

using macOS 14 (Sonoma)

**Comment by ihateblueb** [comment]
i just removed the colors, i was planning on removing them anyway because they were inconsistent and kind of weird. i don't have a mac to test this on though so let me know if that helped or not (didnt know mentioning this issue would close it, my bad)

**Comment by jmshgs** [comment]
worked this time! the macOS binary you attached to the release didn't work so I'll put mine here if you want to add it. 
[cobalt-cli.zip](https://github.com/ihateblueb/cobalt-cli/files/12654623/cobalt-cli.zip)
